package event

import "errors"

// Sentinel errors returned by Event.Validate(). Callers should use errors.Is
// to check for specific validation failures rather than comparing strings.
//
// Which event types trigger which sentinel:
//
//	ErrMissingEventID    — all event types (ID is auto-generated by New(); only
//	                       absent if the event was constructed without New()).
//	ErrMissingEventType  — all event types (Type is required on every event).
//	ErrMissingClientID   — all event types (Level 1, 2, and 3 all require ClientID).
//	ErrMissingWorkflowID — Level 1 (workflow.published), Level 2 (run.*), Level 3 (node.*).
//	ErrMissingRunID      — Level 2 (run.started, run.ended) and Level 3 (node.*) events.
//	ErrMissingNodeID     — Level 3 events only (node.triggered, node.started, node.ended).
//
// Field requirements by level:
//   - Level 1 (workflow.published): ClientID + WorkflowID.
//   - Level 2 (run.started, run.ended): ClientID + WorkflowID + RunID.
//   - Level 3 (node.*):               ClientID + WorkflowID + RunID + NodeID.
var (
	// ErrMissingEventID is returned by Validate when the event ID is empty.
	// The ID is the NATS JetStream deduplication key; it must be set on every
	// event. Use New() to create events; it auto-generates a UUID for the ID.
	ErrMissingEventID = errors.New("event_id is required")

	// ErrMissingEventType is returned by Validate when Type is empty.
	// Type must be one of the constants defined in this package
	// (e.g. TypeWorkflowPublished, TypeRunStarted, TypeNodeEnded).
	ErrMissingEventType = errors.New("event type is required")

	// ErrMissingClientID is returned by Validate when ClientID is empty.
	// ClientID is the tenant identifier; it is required on all event levels
	// for multi-tenancy scoping in the Athena Elasticsearch index.
	ErrMissingClientID = errors.New("client_id is required")

	// ErrMissingWorkflowID is returned by Validate when WorkflowID is empty.
	// WorkflowID is required for Level 1, 2, and 3 events.
	ErrMissingWorkflowID = errors.New("workflow_id is required")

	// ErrMissingRunID is returned by Validate when RunID is empty on a Level 2
	// (run.*) or Level 3 (node.*) event. RunID is not required for Level 1
	// (workflow.published) events.
	ErrMissingRunID = errors.New("run_id is required")

	// ErrMissingNodeID is returned by Validate when NodeID is empty on a Level 3
	// (node.triggered, node.started, node.ended) event. NodeID is not required
	// for Level 1 or Level 2 events.
	ErrMissingNodeID = errors.New("node_id is required for plugin events")
)
